name: 'Flexion Tech Radar Generator'
description: 'Generates a tech radar based on the provided folder. Initially based in the AOE radar'
author: David Vega <dvega@flexion.us>


#TODO: Add parameter for input format for the radar; 
#      Markdown is implied, under the AOE radar format "<version>/*.md",
#      but JSON is also supported
#TODO: Parametrize radar engine; AOE Radar is implied
inputs:

  directory:
    description: 'Folder containing the tech radar data'
    required: true

  artifact_name:
    description: 'Name of the artifact to upload (optional)'
    required: false

  publish_to_pages:
    description: 'Publish to GitHub Pages (optional)'
    required: false
    default: "false"

  public_url:
    description: 'Public URL used for rendering and publishing the radar'
    required: false
    default: "./build"

  radar_name:
    description: 'Name of the radar (optional)'
    required: false
    default: "Flexion Tech Radar"

outputs:
  pages_url:
    description: 'URL of the GitHub Pages deployment'
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    #TODO: Parametrize radar version
    #TODO: Extract to script
    - name: Install AOE radar
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        export PUBLIC_URL=${{ inputs.public_url }}
        export REACT_APP_RADAR_NAME="${{ inputs.radar_name }}"

        pwd
        ls -al

        # If no package.json is present, copy the one from this action
        if [ ! -f package.json ]; then
          cp -r $GITHUB_ACTION_PATH/package.json .
        fi

        cat package.json

        # Use jq to generate config.json with basepath, default is "basePath": "/techradar"
        jq \
          -n \
          --arg basepath "${PUBLIC_URL}" \
          '{basePath: $basepath}' > config.json

        cat config.json

        npm install

        ls node_modules/.bin  # Debug: list the contents of node_modules/.bin

        PUBLIC_URL="${{ inputs.public_url }}"
        npm run build


    - name: Upload artifact
      if: ${{ inputs.publish_to_pages == 'false' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact_name || 'tech-radar' }}
        path: "${{ inputs.directory }}/build"

    - name: Setup Pages
      if: ${{ inputs.publish_to_pages == 'true' }}
      uses: actions/configure-pages@v3

    - name: Upload artifact to Pages
      if: ${{ inputs.publish_to_pages == 'true' }}
      uses: actions/upload-pages-artifact@v2
      with:
        path: ${{ inputs.directory }}/build

    #TODO: Add more deployment targets
    - name: Deploy to GitHub Pages
      if: ${{ inputs.publish_to_pages == 'true' }}
      id: deployment
      uses: actions/deploy-pages@v2